#!/usr/bin/env bash
# Escribe BACKEND/.env.staging desde variables de entorno (CI / deploy).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TARGET="$ROOT/BACKEND/.env.staging"

required_vars=(
  POSTGRES_HOST
  POSTGRES_PASSWORD
  JWT_SECRET
)

for var in "${required_vars[@]}"; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: falta variable requerida $var" >&2
    exit 1
  fi
done

cat >"$TARGET" <<EOF
# Generado por scripts/ci/write-staging-env.sh — no commitear
COMPOSE_PROJECT_NAME=e-vidente

POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
POSTGRES_DB=${POSTGRES_DB:-postgres}
POSTGRES_USER=${POSTGRES_USER:-postgres}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_SSL=true
POSTGRES_POOL_MAX=${POSTGRES_POOL_MAX:-8}

BACKEND_PORT=${BACKEND_PORT:-3010}
BACKEND_HOST=${BACKEND_HOST:-localhost}
BACKEND_BASE_URL=${BACKEND_BASE_URL:-}
NODE_ENV=${NODE_ENV:-development}

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS:-10}

EMAIL_ENABLED=${EMAIL_ENABLED:-false}
BREVO_API_KEY=${BREVO_API_KEY:-}
BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL:-evidente2026@gmail.com}
BREVO_SENDER_NAME=${BREVO_SENDER_NAME:-E-VIDENTE}
EMAIL_CRON_SECRET=${EMAIL_CRON_SECRET:-staging_ci_secret}
EMAIL_TIMEZONE=${EMAIL_TIMEZONE:-America/Argentina/Buenos_Aires}
EMAIL_PENDING_STALE_MINUTES=${EMAIL_PENDING_STALE_MINUTES:-15}
EMAIL_BATCH_CONCURRENCY=${EMAIL_BATCH_CONCURRENCY:-5}
EMAIL_RETRY_MAX_ATTEMPTS=${EMAIL_RETRY_MAX_ATTEMPTS:-3}
EMAIL_RETRY_MAX_AGE_HOURS=${EMAIL_RETRY_MAX_AGE_HOURS:-48}
EMAIL_RETRY_BATCH_LIMIT=${EMAIL_RETRY_BATCH_LIMIT:-50}
EMAIL_REQUEST_TIMEOUT_MS=${EMAIL_REQUEST_TIMEOUT_MS:-15000}
EMAIL_REQUEST_MAX_ATTEMPTS=${EMAIL_REQUEST_MAX_ATTEMPTS:-3}
EMAIL_REQUEST_RETRY_BASE_MS=${EMAIL_REQUEST_RETRY_BASE_MS:-500}
EMAIL_PROCESS_ON_STARTUP=${EMAIL_PROCESS_ON_STARTUP:-false}
EMAIL_PENDING_WELCOME_BATCH_LIMIT=${EMAIL_PENDING_WELCOME_BATCH_LIMIT:-25}
BREVO_WEBHOOK_SECRET=${BREVO_WEBHOOK_SECRET:-}

SUPABASE_PROJECT_REF=${SUPABASE_PROJECT_REF:-}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY:-}
EOF

echo "Wrote $TARGET"
