name: PR
run-name: "${{ format('{0} -> {1}', github.head_ref, github.base_ref) }}"

on:
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: godot-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pull-request-validation:
    name: Checks
    uses: ./.github/workflows/ci-shared.yml
